In [1]:
import pandas as pd # import modules

In [4]:
df = pd.read_csv('brazillian_states.txt', delimiter=':') # Convert txt file to csv
df

    AC                  Acre
0   AL               Alagoas
1   AM              Amazonas
2   AP                 Amapá
3   BA                 Bahia
4   CE                 Ceará
5   DF      Distrito Federal
6   ES        Espírito Santo
7   GO                 Goiás
8   MA              Maranhão
9   MG          Minas Gerais
10  MS    Mato Grosso do Sul
11  MT           Mato Grosso
12  PA                  Pará
13  PB               Paraíba
14  PE            Pernambuco
15  PI                 Piauí
16  PR                Paraná
17  RJ        Rio de Janeiro
18  RN   Rio Grande do Norte
19  RO              Rondônia
20  RR               Roraima
21  RS     Rio Grande do Sul
22  SC        Santa Catarina
23  SE               Sergipe
24  SP             São Paulo
25  TO             Tocantins

In [5]:
df.to_csv('brazillian_states.csv', index=False) # export file as csv